<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="QRCoder" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CotelNet.Application/CotelNet.Application.csproj" />
    <ProjectReference Include="../CotelNet.Domain/CotelNet.Domain.csproj" />
  </ItemGroup>
</Project>
